# src/test/resources/application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # H2 인메모리 DB 설정
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # 테스트 시 테이블 자동 생성 및 삭제
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  sql:
    init:
      mode: never # 테스트 시 SQL 초기화 방지 (필요에 따라 설정)

  # Kakao OAuth2 설정도 테스트용으로 필요한 경우 여기에 추가
  security:
    oauth2:
      client:
        registration:
          kakao-customer:
            provider: kakao
            client-id: test-client-id-customer # 실제 ID와 달라도 무방
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao-customer # 로컬 테스트용 URI
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname
          kakao-staff:
            provider: kakao
            client-id: test-client-id-staff # 실제 ID와 달라도 무방
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao-staff # 로컬 테스트용 URI
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname

  # JWT secret도 테스트에 필요하면 여기에 추가
  jwt:
    secret: test_jwt_secret_for_local_testing_and_github_actions_build # 테스트용 임의 값